<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Kode OTP Terkirim</name>
   <tag></tag>
   <elementGuidId>acf19987-bc68-4adf-9eb1-55dee0ddde91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='safe-area']/div[2]/div[2]/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.OtpForm_form-header__3aS9S</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e70c739d-3e32-4740-acd4-0e6c9f28c53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OtpForm_form-header__3aS9S</value>
      <webElementGuid>fc2e43b4-7801-4267-8435-0b55e5fa345c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kode OTP Terkirim</value>
      <webElementGuid>7fddb426-498b-4379-8acb-af8a87443b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;safe-area&quot;)/div[@class=&quot;HeaderFooter_header-gap__3du2n&quot;]/div[@class=&quot;superapp-container content&quot;]/div[@class=&quot;container_Eq-qi&quot;]/h2[@class=&quot;OtpForm_form-header__3aS9S&quot;]</value>
      <webElementGuid>ab9af07d-49ef-4b1d-90d4-31963dd96bac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='safe-area']/div[2]/div[2]/div/h2</value>
      <webElementGuid>eeb901ea-291b-4afb-a1f1-22ae20be09fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi No. Handphone'])[1]/following::h2[1]</value>
      <webElementGuid>dedf7168-6065-4347-9659-1d9a991924ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::h2[1]</value>
      <webElementGuid>6f112a87-d2ad-4da4-aa1c-c585dd7158ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='****-*****000'])[1]/preceding::h2[1]</value>
      <webElementGuid>cbac1ca1-231d-4e87-8c42-0a7d3e597a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='('])[1]/preceding::h2[1]</value>
      <webElementGuid>a3a92d8c-b8dd-4ffa-b5ec-93fdabf1cb58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kode OTP Terkirim']/parent::*</value>
      <webElementGuid>2ce666fe-739c-49f1-9e7f-e13b27822579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>196faf98-cd15-46a6-b2a3-bbd951460cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Kode OTP Terkirim' or . = 'Kode OTP Terkirim')]</value>
      <webElementGuid>82e1a13d-543b-4841-90ac-35d58a2e2784</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
